export type NarrativeSourceTable =
  | "audits"
  | "controls"
  | "applications"
  | "third_parties"
  | "rcsa_records"
  | "issues"
  | "monitoring_results"
  | "prior_audit_findings"
  | "audit_documents"
  | "business_units";

export type NarrativeTokenMapping = {
  token: string;
  section: string;
  description: string;
  required: boolean;
  sourceTables: NarrativeSourceTable[];
  sourceFields: string[];
  transform: string;
};

export const planningNarrativeTokenMappings: NarrativeTokenMapping[] = [
  {
    token: "audit_name",
    section: "1. Audit Overview",
    description: "Display name of the audit.",
    required: true,
    sourceTables: ["audits"],
    sourceFields: ["audits.name"],
    transform: "Direct map from audit record.",
  },
  {
    token: "audit_period",
    section: "1. Audit Overview",
    description: "Formatted audit period label.",
    required: true,
    sourceTables: ["audits"],
    sourceFields: ["audits.period_start", "audits.period_end"],
    transform: "Format period_start and period_end into a readable range.",
  },
  {
    token: "current_phase",
    section: "1. Audit Overview",
    description: "Current audit phase.",
    required: true,
    sourceTables: ["audits"],
    sourceFields: ["audits.active_phase"],
    transform: "Normalize to Planning, Fieldwork, or Reporting.",
  },
  {
    token: "audit_status",
    section: "1. Audit Overview",
    description: "Current audit status.",
    required: true,
    sourceTables: ["audits"],
    sourceFields: ["audits.status"],
    transform: "Direct map.",
  },
  {
    token: "source_system",
    section: "1. Audit Overview",
    description: "Primary system label for imported audit data.",
    required: false,
    sourceTables: ["audits", "controls", "applications", "third_parties"],
    sourceFields: ["audits.source_system", "controls.source_system"],
    transform: "Prefer audit source_system; otherwise summarize dominant imported source_system.",
  },
  {
    token: "planning_narrative_summary",
    section: "1. Audit Overview",
    description: "Short executive summary paragraph for the planning narrative.",
    required: true,
    sourceTables: ["audits", "controls", "rcsa_records", "issues", "monitoring_results", "prior_audit_findings"],
    sourceFields: [
      "audits.active_phase",
      "controls.status",
      "controls.risk_rating",
      "rcsa_records.residual_risk_rating",
      "issues.severity",
      "monitoring_results.severity",
      "prior_audit_findings.severity",
    ],
    transform: "AI-generated narrative from structured risk and readiness summary.",
  },
  {
    token: "audit_focus_areas",
    section: "2. Audit Objective and Scope Context",
    description: "Named process or risk areas that define the audit focus.",
    required: true,
    sourceTables: ["controls", "applications", "rcsa_records"],
    sourceFields: ["controls.control_name", "applications.application_name", "rcsa_records.risk_statement"],
    transform: "Summarize top control themes, applications, and risk statements into 2-5 focus areas.",
  },
  {
    token: "business_units_in_scope",
    section: "2. Audit Objective and Scope Context",
    description: "Business units in the current audit perimeter.",
    required: true,
    sourceTables: ["controls", "applications", "third_parties", "rcsa_records", "business_units"],
    sourceFields: [
      "controls.business_unit_id",
      "applications.business_unit_id",
      "third_parties.business_unit_id",
      "rcsa_records.business_unit_id",
      "business_units.name",
    ],
    transform: "Resolve business unit ids and return distinct business unit names.",
  },
  {
    token: "control_count",
    section: "2. Audit Objective and Scope Context",
    description: "Total count of in-scope controls.",
    required: true,
    sourceTables: ["controls"],
    sourceFields: ["controls.id"],
    transform: "Count controls for the audit.",
  },
  {
    token: "business_context_summary",
    section: "2. Audit Objective and Scope Context",
    description: "Narrative business context for the audit.",
    required: false,
    sourceTables: ["applications", "third_parties", "controls"],
    sourceFields: ["applications.application_name", "third_parties.third_party_name", "controls.control_name"],
    transform: "AI-generated paragraph summarizing operating context, systems, vendors, and processes in scope.",
  },
  {
    token: "application_count",
    section: "3. Planning Inputs Considered",
    description: "Count of imported application records.",
    required: true,
    sourceTables: ["applications"],
    sourceFields: ["applications.id"],
    transform: "Count applications for the audit.",
  },
  {
    token: "third_party_count",
    section: "3. Planning Inputs Considered",
    description: "Count of imported third-party records.",
    required: true,
    sourceTables: ["third_parties"],
    sourceFields: ["third_parties.id"],
    transform: "Count third parties for the audit.",
  },
  {
    token: "rcsa_count",
    section: "3. Planning Inputs Considered",
    description: "Count of imported RCSA records.",
    required: true,
    sourceTables: ["rcsa_records"],
    sourceFields: ["rcsa_records.id"],
    transform: "Count RCSA rows for the audit.",
  },
  {
    token: "issue_count",
    section: "3. Planning Inputs Considered",
    description: "Count of imported issue records.",
    required: true,
    sourceTables: ["issues"],
    sourceFields: ["issues.id"],
    transform: "Count issues for the audit.",
  },
  {
    token: "monitoring_result_count",
    section: "3. Planning Inputs Considered",
    description: "Count of imported monitoring results.",
    required: true,
    sourceTables: ["monitoring_results"],
    sourceFields: ["monitoring_results.id"],
    transform: "Count monitoring results for the audit.",
  },
  {
    token: "prior_finding_count",
    section: "3. Planning Inputs Considered",
    description: "Count of imported prior findings.",
    required: true,
    sourceTables: ["prior_audit_findings"],
    sourceFields: ["prior_audit_findings.id"],
    transform: "Count prior findings for the audit.",
  },
  {
    token: "planning_source_summary",
    section: "3. Planning Inputs Considered",
    description: "Narrative summary of imported planning sources.",
    required: true,
    sourceTables: ["applications", "third_parties", "issues", "rcsa_records", "monitoring_results", "prior_audit_findings"],
    sourceFields: [
      "applications.application_name",
      "third_parties.third_party_name",
      "issues.issue_summary",
      "rcsa_records.risk_statement",
      "monitoring_results.title",
      "prior_audit_findings.prior_audit_name",
    ],
    transform: "AI-generated summary of the imported planning inputs considered during planning.",
  },
  {
    token: "planning_source_highlights",
    section: "3. Planning Inputs Considered",
    description: "Bullet-style planning input highlights.",
    required: false,
    sourceTables: ["applications", "third_parties", "issues", "rcsa_records", "monitoring_results", "prior_audit_findings"],
    sourceFields: [
      "applications.source_payload",
      "third_parties.source_payload",
      "issues.source_payload",
      "rcsa_records.source_payload",
      "monitoring_results.source_payload",
      "prior_audit_findings.source_payload",
    ],
    transform: "Generate 3-6 concise highlights from the most relevant imported records and payload fields.",
  },
  {
    token: "high_risk_theme_summary",
    section: "4. Risk Assessment Summary",
    description: "Summary of the top risk themes from imported records.",
    required: true,
    sourceTables: ["rcsa_records", "issues", "monitoring_results", "prior_audit_findings", "controls"],
    sourceFields: [
      "rcsa_records.residual_risk_rating",
      "issues.severity",
      "monitoring_results.severity",
      "prior_audit_findings.severity",
      "controls.risk_rating",
    ],
    transform: "AI-generated summary prioritizing highest-risk imported themes.",
  },
  {
    token: "high_risk_rcsa_count",
    section: "4. Risk Assessment Summary",
    description: "Count of high-risk RCSA records.",
    required: true,
    sourceTables: ["rcsa_records"],
    sourceFields: ["rcsa_records.residual_risk_rating"],
    transform: "Count RCSA rows where residual_risk_rating = high.",
  },
  {
    token: "medium_risk_rcsa_count",
    section: "4. Risk Assessment Summary",
    description: "Count of medium-risk RCSA records.",
    required: true,
    sourceTables: ["rcsa_records"],
    sourceFields: ["rcsa_records.residual_risk_rating"],
    transform: "Count RCSA rows where residual_risk_rating = medium.",
  },
  {
    token: "rcsa_risk_detail",
    section: "4. Risk Assessment Summary",
    description: "Narrative detail from imported RCSA statements and key controls.",
    required: true,
    sourceTables: ["rcsa_records"],
    sourceFields: ["rcsa_records.risk_statement", "rcsa_records.key_controls", "rcsa_records.residual_risk_rating"],
    transform: "AI-generated paragraph summarizing the most relevant RCSA themes and linked key controls.",
  },
  {
    token: "issue_and_finding_summary",
    section: "4. Risk Assessment Summary",
    description: "Narrative summary of imported issues and prior findings.",
    required: true,
    sourceTables: ["issues", "prior_audit_findings"],
    sourceFields: [
      "issues.issue_summary",
      "issues.root_cause",
      "issues.remediation_progress",
      "prior_audit_findings.finding_description",
      "prior_audit_findings.status",
    ],
    transform: "AI-generated summary of recurring issue/finding themes, remediation status, and planning implications.",
  },
  {
    token: "monitoring_signal_summary",
    section: "4. Risk Assessment Summary",
    description: "Narrative summary of imported monitoring results.",
    required: false,
    sourceTables: ["monitoring_results"],
    sourceFields: ["monitoring_results.title", "monitoring_results.summary", "monitoring_results.severity", "monitoring_results.status"],
    transform: "AI-generated paragraph describing current-state signals from monitoring results.",
  },
  {
    token: "controls_with_assigned_owner_count",
    section: "5. Control Environment and Audit Readiness",
    description: "Count of controls with an assigned audit owner.",
    required: true,
    sourceTables: ["controls"],
    sourceFields: ["controls.assigned_owner_user_id"],
    transform: "Count controls where assigned_owner_user_id is not null.",
  },
  {
    token: "controls_with_budget_count",
    section: "5. Control Environment and Audit Readiness",
    description: "Count of controls with planned hours assigned.",
    required: true,
    sourceTables: ["controls"],
    sourceFields: ["controls.assigned_planned_hours"],
    transform: "Count controls where assigned_planned_hours is not null.",
  },
  {
    token: "controls_with_due_date_count",
    section: "5. Control Environment and Audit Readiness",
    description: "Count of controls with due dates assigned.",
    required: true,
    sourceTables: ["controls"],
    sourceFields: ["controls.assigned_due_date"],
    transform: "Count controls where assigned_due_date is not null.",
  },
  {
    token: "planning_readiness_summary",
    section: "5. Control Environment and Audit Readiness",
    description: "Narrative readiness summary from current setup state.",
    required: true,
    sourceTables: ["controls", "audit_documents", "audits"],
    sourceFields: [
      "controls.assigned_owner_user_id",
      "controls.assigned_planned_hours",
      "controls.assigned_due_date",
      "audit_documents.document_type",
      "audit_documents.status",
      "audits.active_phase",
    ],
    transform: "AI-generated paragraph summarizing setup completeness and planning readiness.",
  },
  {
    token: "open_planning_gaps",
    section: "5. Control Environment and Audit Readiness",
    description: "Open setup items before fieldwork.",
    required: true,
    sourceTables: ["controls", "audit_documents"],
    sourceFields: [
      "controls.assigned_owner_user_id",
      "controls.assigned_planned_hours",
      "controls.assigned_due_date",
      "audit_documents.document_type",
      "audit_documents.status",
    ],
    transform: "Generate bullet list of missing owners, budgets, due dates, and incomplete planning artifacts.",
  },
  {
    token: "planning_budget_hours",
    section: "6. Budget and Resource Considerations",
    description: "Planned hours for planning phase.",
    required: true,
    sourceTables: ["audits"],
    sourceFields: ["audits.planning_budget_hours"],
    transform: "Direct map from audit phase budget field.",
  },
  {
    token: "fieldwork_budget_hours",
    section: "6. Budget and Resource Considerations",
    description: "Planned hours for fieldwork phase.",
    required: true,
    sourceTables: ["audits"],
    sourceFields: ["audits.fieldwork_budget_hours"],
    transform: "Direct map from audit phase budget field.",
  },
  {
    token: "reporting_budget_hours",
    section: "6. Budget and Resource Considerations",
    description: "Planned hours for reporting phase.",
    required: true,
    sourceTables: ["audits"],
    sourceFields: ["audits.reporting_budget_hours"],
    transform: "Direct map from audit phase budget field.",
  },
  {
    token: "budget_narrative",
    section: "6. Budget and Resource Considerations",
    description: "Narrative explaining the phase budget profile.",
    required: true,
    sourceTables: ["audits", "controls"],
    sourceFields: [
      "audits.planning_budget_hours",
      "audits.fieldwork_budget_hours",
      "audits.reporting_budget_hours",
      "controls.assigned_planned_hours",
      "controls.planned_hours",
    ],
    transform: "AI-generated summary of the current phase budget posture and resource expectations.",
  },
  {
    token: "budget_gap_summary",
    section: "6. Budget and Resource Considerations",
    description: "Summary of budgeted hours not yet set or aligned.",
    required: true,
    sourceTables: ["audits", "controls"],
    sourceFields: [
      "audits.planning_budget_hours",
      "audits.fieldwork_budget_hours",
      "audits.reporting_budget_hours",
      "controls.assigned_planned_hours",
    ],
    transform: "Summarize missing phase budgets and control-level hour setup gaps.",
  },
  {
    token: "scope_focus_summary",
    section: "7. Proposed Audit Focus and Scope Implications",
    description: "Overall proposed scope focus based on imported planning data.",
    required: true,
    sourceTables: ["rcsa_records", "issues", "monitoring_results", "prior_audit_findings", "applications", "third_parties"],
    sourceFields: [
      "rcsa_records.risk_statement",
      "issues.issue_summary",
      "monitoring_results.summary",
      "prior_audit_findings.finding_description",
      "applications.application_name",
      "third_parties.third_party_name",
    ],
    transform: "AI-generated summary of where the audit should focus based on imported risk indicators.",
  },
  {
    token: "deep_testing_areas",
    section: "7. Proposed Audit Focus and Scope Implications",
    description: "Areas that warrant deeper audit coverage.",
    required: true,
    sourceTables: ["rcsa_records", "issues", "monitoring_results", "prior_audit_findings"],
    sourceFields: [
      "rcsa_records.residual_risk_rating",
      "issues.severity",
      "monitoring_results.severity",
      "prior_audit_findings.severity",
    ],
    transform: "Generate bullet list of areas requiring deeper testing based on highest-risk imported signals.",
  },
  {
    token: "targeted_validation_areas",
    section: "7. Proposed Audit Focus and Scope Implications",
    description: "Areas that should remain in scope but with targeted validation only.",
    required: false,
    sourceTables: ["applications", "third_parties", "rcsa_records"],
    sourceFields: ["applications.criticality", "third_parties.criticality", "rcsa_records.residual_risk_rating"],
    transform: "Generate targeted-but-not-expanded areas from moderate or supporting risk signals.",
  },
  {
    token: "out_of_scope_or_limited_scope_areas",
    section: "7. Proposed Audit Focus and Scope Implications",
    description: "Areas not expected to require broad coverage.",
    required: false,
    sourceTables: ["applications", "third_parties", "monitoring_results", "prior_audit_findings"],
    sourceFields: ["applications.application_name", "third_parties.third_party_name", "monitoring_results.status", "prior_audit_findings.status"],
    transform: "AI-generated list of areas suitable for limited scope or watchlist treatment.",
  },
  {
    token: "audit_approach_summary",
    section: "8. Planned Audit Approach",
    description: "Narrative of the proposed audit approach.",
    required: true,
    sourceTables: ["controls", "applications", "third_parties", "rcsa_records"],
    sourceFields: [
      "controls.control_name",
      "controls.control_frequency",
      "applications.application_name",
      "third_parties.service_category",
      "rcsa_records.key_controls",
    ],
    transform: "AI-generated paragraph describing walkthrough, testing, evidence, and sampling approach.",
  },
  {
    token: "likely_procedures",
    section: "8. Planned Audit Approach",
    description: "Expected audit procedures based on imported data.",
    required: true,
    sourceTables: ["controls", "applications", "third_parties", "rcsa_records", "monitoring_results"],
    sourceFields: [
      "controls.control_name",
      "controls.testing_sample_size",
      "applications.application_name",
      "third_parties.third_party_name",
      "monitoring_results.title",
    ],
    transform: "Generate a procedure list aligned to imported controls, systems, vendors, and signals.",
  },
  {
    token: "evidence_expectations",
    section: "8. Planned Audit Approach",
    description: "Expected evidence and data needs.",
    required: false,
    sourceTables: ["controls", "applications", "third_parties", "issues", "monitoring_results"],
    sourceFields: [
      "controls.source_payload",
      "applications.source_payload",
      "third_parties.source_payload",
      "issues.source_payload",
      "monitoring_results.source_payload",
    ],
    transform: "Generate a concise list of data, reports, trackers, and artifacts expected during execution.",
  },
  {
    token: "planning_dependencies",
    section: "9. Key Dependencies, Assumptions, and Open Items",
    description: "Dependencies before fieldwork can proceed cleanly.",
    required: true,
    sourceTables: ["controls", "audit_documents"],
    sourceFields: [
      "controls.assigned_owner_user_id",
      "controls.assigned_due_date",
      "controls.assigned_planned_hours",
      "audit_documents.document_type",
      "audit_documents.status",
    ],
    transform: "Generate dependency list from missing setup and open planning artifacts.",
  },
  {
    token: "planning_assumptions",
    section: "9. Key Dependencies, Assumptions, and Open Items",
    description: "Narrative assumptions used in planning.",
    required: false,
    sourceTables: ["audits", "controls", "applications", "third_parties"],
    sourceFields: [
      "audits.active_phase",
      "controls.status",
      "applications.lifecycle_status",
      "third_parties.lifecycle_status",
    ],
    transform: "AI-generated assumptions list grounded in current imported record states.",
  },
  {
    token: "pre_fieldwork_open_items",
    section: "9. Key Dependencies, Assumptions, and Open Items",
    description: "Remaining open items before fieldwork.",
    required: true,
    sourceTables: ["controls", "audit_documents", "issues"],
    sourceFields: [
      "controls.assigned_owner_user_id",
      "controls.assigned_due_date",
      "controls.assigned_planned_hours",
      "audit_documents.status",
      "issues.status",
    ],
    transform: "Generate open-item list relevant to fieldwork readiness.",
  },
  {
    token: "leadership_decision_points",
    section: "10. Leadership Decision Points",
    description: "Specific decision asks for leadership.",
    required: true,
    sourceTables: ["rcsa_records", "issues", "monitoring_results", "prior_audit_findings", "controls", "audit_documents"],
    sourceFields: [
      "rcsa_records.residual_risk_rating",
      "issues.severity",
      "monitoring_results.severity",
      "prior_audit_findings.severity",
      "controls.assigned_planned_hours",
      "audit_documents.status",
    ],
    transform: "AI-generated list of decision asks based on risk concentration and planning readiness gaps.",
  },
  {
    token: "conclusion_summary",
    section: "11. Conclusion",
    description: "Closing conclusion sentence fragment.",
    required: true,
    sourceTables: ["audits", "controls", "rcsa_records", "issues", "monitoring_results", "prior_audit_findings", "audit_documents"],
    sourceFields: [
      "audits.active_phase",
      "controls.status",
      "rcsa_records.residual_risk_rating",
      "issues.status",
      "monitoring_results.status",
      "prior_audit_findings.status",
      "audit_documents.status",
    ],
    transform: "AI-generated concluding summary grounded in planning readiness, risk themes, and open items.",
  },
];

export const planningNarrativeTemplateSections = [
  {
    section: "Audit Overview",
    purpose: "Establish audit identity, phase, and executive planning summary.",
  },
  {
    section: "Audit Objective and Scope Context",
    purpose: "Define the audit objective, perimeter, and business context using imported data.",
  },
  {
    section: "Planning Inputs Considered",
    purpose: "Document the imported source inputs used to develop the narrative.",
  },
  {
    section: "Risk Assessment Summary",
    purpose: "Summarize risk themes from RCSAs, issues, findings, and monitoring results.",
  },
  {
    section: "Control Environment and Audit Readiness",
    purpose: "Describe current setup completeness and planning gaps before fieldwork.",
  },
  {
    section: "Budget and Resource Considerations",
    purpose: "Tie phase budgets and budget gaps to the narrative.",
  },
  {
    section: "Proposed Audit Focus and Scope Implications",
    purpose: "Translate imported data into scoped audit focus areas.",
  },
  {
    section: "Planned Audit Approach",
    purpose: "Describe likely procedures, evidence expectations, and approach.",
  },
  {
    section: "Key Dependencies, Assumptions, and Open Items",
    purpose: "Identify remaining dependencies and assumptions before execution.",
  },
  {
    section: "Leadership Decision Points",
    purpose: "Surface the decisions leadership should make during planning.",
  },
  {
    section: "Conclusion",
    purpose: "Close the narrative with a concise planning conclusion.",
  },
] as const;
